### ISSUE TITLE
Segment costs have unintuitive interface

### ISSUE THREAD

**Issue by fairbrot** [STOR-i/Changepoints.jl#11]
Consider the following cost function:
cost = NormalMeanSegment(x)

Now, the function call cost(s,t) gives the cost of the points x[s+1], ... x[t] rather than x[s], ..., x[t]. This is unintuitive, and may cause problems when users write their own cost functions. It certainly caused me some confusion when working on the binary segmentation algorithm.

**Comment by bardwell** [comment]
that's a good point think we changed them so it gave the same answers as the R package 

Its potentially because the pelt algorithm sets off with a chpt candidate (the set R) at 0 (meaning no changepoint) and to evaluate the cost from 0 to t say really in data terms means from data[1:t] i'm not sure if that is a good enough reason to keep them that way or not?

Also regarding cost(t,t) = NaN: this is probably ok becasue we dont want a segment with a single data point in, if this is cropping up in BS we can fix it so that segments have to have length >2.

**Comment by fairbrot** [comment]
I've now fixed the BS function to work with the cost functions as they currently are. If this change can be made while still having output consistent with R I think it would definitely be worth doing. Perhaps after we have rigourous unit tests set up as this type of change is likely to put bugs in the code.

**Comment by bardwell** [comment]
Nice one, yes i agree

**Comment by kayleahaynes** [comment]
The reason it is x[s+1] to x[t] is because we define a segment as being the first point after a changepoint up to the next changepoint.  That is there will be a changepoint at s and a changepoint at t.

**Comment by fairbrot** [comment]
Ok, we'll stick with the changepoint convention for now. It should be fine as long as this is explained in the documentation.
