### ISSUE TITLE
Domain error when running PELT function

### ISSUE THREAD

**Issue by mostwanted7** [STOR-i/Changepoints.jl#29]
`pelt_cps, cost = @PELT data2 Normal(:?, :?)`

Where data 2 is a set of data (formatted as Float64, only positive decimal numbers)

<img width="525" alt="domainerror" src="https://user-images.githubusercontent.com/30668278/115005581-4c7eba00-9ea8-11eb-93fa-27848553ebe9.PNG">

**Comment by fairbrot** [comment]
Sounds like a numerical error - should be fixable. Does this happen often? How was `data2` generated here?

**Comment by mostwanted7** [comment]
> Sounds like a numerical error - should be fixable. Does this happen often? How was `data2` generated here?

Does not happen very often, I tried this function with some small data and it worked properly. 
`Data 2 `was a raw read of electric current from an electronic device, which I just formatted as an array that contains Float64 values. However, this array contains 25 000 values, so maybe it has something to do with that (size of the array given)?

**Comment by fairbrot** [comment]
25 000 does seem like quite a long time series. Would downsampling make sense in this case? Do you have any views on this @Dom-Owens-UoB ?

**Comment by Dom-Owens-UoB** [comment]
I think the problem is the line `sig = ...`,  in  `NormalMeanVarSegment` called by the PELT macro. 
```
function NormalMeanVarSegment(data::Array{Float64})
    cd = zero_cumsum(data)
    cd_2 = zero_cumsum(x -> x^2, data)
    function cost(s::Int64, t::Int64)
      mu = (cd[t + 1] - cd[s + 1]) / (t - s)
      sig =  ( cd_2[t+1] - cd_2[s+1] ) / (t-s) - mu^2 
      return (t-s)*log(sig) + (cd_2[t+1] - cd_2[s+1])/sig - 2*(cd[t+1] - cd[s+1])*mu/sig + ((t-s)*mu^2)/sig
    end
    return cost
end
```

If the data has stretches with identical observations, the result will be negative, resulting in the domain error.  I've enforced non-negativity with `sig = abs.( ( cd_2[t+1] - cd_2[s+1] ) / (t-s) - mu^2 )`, but as you say downsampling would be a sensible way of avoiding these stretches, or manually inspecting for them.
